//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIED
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumno
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Alumno()
        {
            this.Avisoes = new HashSet<Aviso>();
            this.Calificaciones = new HashSet<Calificacione>();
            this.SolicitudBajas = new HashSet<SolicitudBaja>();
        }
    
        public int IDAlumno { get; set; }
        public string NomAlumno { get; set; }
        public string ApePatAlumno { get; set; }
        public string ApeMatAlumno { get; set; }
        public string TelAlumno { get; set; }
        public Nullable<System.DateTime> IngresoAlumno { get; set; }
        public Nullable<int> IDTipoAlumno { get; set; }
        public string FotoAlumno { get; set; }
        public string FotoAlumnoCredencial { get; set; }
        public string CalleAlumno { get; set; }
        public string NumeroAlumno { get; set; }
        public string ColoniaAlumno { get; set; }
        public string CodigoPostalAlumno { get; set; }
        public Nullable<int> IDMunicipioAlumno { get; set; }
        public string NomPadreAlumno { get; set; }
        public string TelPadreAlumno { get; set; }
        public string NomMadreAlumno { get; set; }
        public string TelMadreAlumno { get; set; }
        public string NomTutorAlumno { get; set; }
        public string TelTutorAlumno { get; set; }
        public Nullable<int> IDDocumentosAlumno { get; set; }
        public Nullable<int> IDEscProAlumno { get; set; }
        public Nullable<byte> RevalidaAlumno { get; set; }
        public Nullable<byte> NuevoAlumno { get; set; }
        public Nullable<System.DateTime> FechaNacAlumno { get; set; }
        public string FechaBaja { get; set; }
        public string CurpAlumno { get; set; }
        public string UsuarioAlumno { get; set; }
        public string ContraseñaAlumno { get; set; }
        public Nullable<int> IDGrupo { get; set; }
        public Nullable<int> IDTurno { get; set; }
        public string Matricula { get; set; }
        public Nullable<int> IDSemestrePreinscripcion { get; set; }
        public string FotoTabla { get; set; }
    
        public virtual DocumentosAlumno DocumentosAlumno { get; set; }
        public virtual EscuelasProcedenciaAlumno EscuelasProcedenciaAlumno { get; set; }
        public virtual Grupos Grupos { get; set; }
        public virtual Municipio Municipio { get; set; }
        public virtual Semestre Semestre { get; set; }
        public virtual TipoAlumno TipoAlumno { get; set; }
        public virtual TurnosEscuela TurnosEscuela { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aviso> Avisoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Calificacione> Calificaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolicitudBaja> SolicitudBajas { get; set; }
    }
}
