//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIED
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asignatura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Asignatura()
        {
            this.Calificaciones = new HashSet<Calificacione>();
            this.GrupoAsignaturas = new HashSet<GrupoAsignatura>();
            this.MaestroGrupos = new HashSet<MaestroGrupos>();
        }
    
        public int IDAsignatura { get; set; }
        public string NomAsig { get; set; }
        public string AbrevAsig { get; set; }
        public Nullable<int> IDSemestreAsig { get; set; }
        public Nullable<int> IDTipoAsig { get; set; }
        public Nullable<int> IDModalidadAsig { get; set; }
        public Nullable<int> IDPlanEstudios { get; set; }
        public Nullable<int> CreditosAsig { get; set; }
        public Nullable<byte> Status { get; set; }
        public string RequisitosAsig { get; set; }
        public Nullable<int> HorasPre { get; set; }
        public Nullable<int> HorasNoPre { get; set; }
        public Nullable<int> Duracion { get; set; }
        public Nullable<int> Proceso { get; set; }
        public Nullable<int> Producto { get; set; }
    
        public virtual ModalidadAsignatura ModalidadAsignatura { get; set; }
        public virtual PlanesEstudio PlanesEstudio { get; set; }
        public virtual Semestre Semestre { get; set; }
        public virtual TipoAsignatura TipoAsignatura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Calificacione> Calificaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GrupoAsignatura> GrupoAsignaturas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaestroGrupos> MaestroGrupos { get; set; }
    }
}
