//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIED
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aviso
    {
        public int IDAviso { get; set; }
        public Nullable<int> IDMaestro { get; set; }
        public Nullable<int> IDAlumno { get; set; }
        public string TextoAviso { get; set; }
        public Nullable<byte> EstadoAviso { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual Maestro Maestro { get; set; }
    }
}
