//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIED
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalificacionesAlumno
    {
        public int IDCalificacionAlum { get; set; }
        public Nullable<int> IDAlumno { get; set; }
        public Nullable<int> IDAsignatura { get; set; }
        public Nullable<int> IDMomento { get; set; }
        public Nullable<int> Calificacion { get; set; }
        public Nullable<int> IDGrupo { get; set; }
        public Nullable<int> Inasistencias { get; set; }
        public Nullable<System.DateTime> FechaCaptura { get; set; }
    }
}
