//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIED
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatosEscuela
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DatosEscuela()
        {
            this.DepartamentosEscuelas = new HashSet<DepartamentosEscuela>();
        }
    
        public int IDEscuela { get; set; }
        public string NombreEsc { get; set; }
        public string ClaveEsc { get; set; }
        public string CalleEsc { get; set; }
        public string NumeroEsc { get; set; }
        public string ColoniaEsc { get; set; }
        public string CodigoPostalEsc { get; set; }
        public Nullable<int> IDMunicipio { get; set; }
        public string TelEscuela { get; set; }
        public string EmailEsc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepartamentosEscuela> DepartamentosEscuelas { get; set; }
    }
}
