//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIED
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartamentosEscuela
    {
        public int IDDepartamentos { get; set; }
        public string NombreDep { get; set; }
        public Nullable<int> IDEncargado { get; set; }
        public Nullable<int> IDEscuela { get; set; }
        public Nullable<byte> StatusDep { get; set; }
    
        public virtual DatosEscuela DatosEscuela { get; set; }
        public virtual Maestro Maestro { get; set; }
    }
}
