//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIED
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentosAlumno
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DocumentosAlumno()
        {
            this.Alumnos = new HashSet<Alumno>();
        }
    
        public int IDDocumentos { get; set; }
        public Nullable<byte> ActaNacimiento { get; set; }
        public Nullable<byte> Fotografias { get; set; }
        public Nullable<byte> Curp { get; set; }
        public Nullable<byte> Constancia { get; set; }
        public Nullable<byte> ComprobanteDomiciliario { get; set; }
        public Nullable<byte> BoletaCalificaciones { get; set; }
        public Nullable<byte> CertificadoParcial { get; set; }
        public Nullable<byte> OficioRevalidacion { get; set; }
        public Nullable<byte> ConstanciaMedia { get; set; }
        public Nullable<byte> CertificadoSecundaria { get; set; }
        public string Otros { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alumno> Alumnos { get; set; }
    }
}
