//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIED
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvaluacionDocente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EvaluacionDocente()
        {
            this.Preguntas_EvaluacionDocente = new HashSet<Preguntas_EvaluacionDocente>();
        }
    
        public int id { get; set; }
        public System.DateTime fecha { get; set; }
        public int idAlumno { get; set; }
        public int idMaestroGrupos { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual MaestroGrupos MaestroGrupos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Preguntas_EvaluacionDocente> Preguntas_EvaluacionDocente { get; set; }
    }
}
