//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIED
{
    using System;
    using System.Collections.Generic;
    
    public partial class GrupoAsignatura
    {
        public int IDGrupoAsig { get; set; }
        public Nullable<int> IDGrupo { get; set; }
        public Nullable<int> IDAsignatura { get; set; }
    
        public virtual Asignatura Asignatura { get; set; }
        public virtual Grupos Grupos { get; set; }
    }
}
