//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIED
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaestroGrupos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MaestroGrupos()
        {
            this.EvaluacionDocentes = new HashSet<EvaluacionDocente>();
        }
    
        public int IDMaestroGrupo { get; set; }
        public Nullable<int> IDMaestro { get; set; }
        public Nullable<int> IDGrupo { get; set; }
        public Nullable<int> IDAsignatura { get; set; }
        public Nullable<int> IDPeriodo { get; set; }
    
        public virtual Asignatura Asignatura { get; set; }
        public virtual Grupos Grupos { get; set; }
        public virtual Maestro Maestro { get; set; }
        public virtual PeriodoEscolar PeriodoEscolar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EvaluacionDocente> EvaluacionDocentes { get; set; }
    }
}
