//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIED
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mensaje
    {
        public int IDMensaje { get; set; }
        public Nullable<int> IDRemitente { get; set; }
        public Nullable<int> IDDestinatario { get; set; }
        public string Asunto { get; set; }
        public string Mensaje1 { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    }
}
