//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIED
{
    using System;
    using System.Collections.Generic;
    
    public partial class Preguntas_EvaluacionDocente
    {
        public int id { get; set; }
        public int idPregunta { get; set; }
        public int idEvaluacionDocente { get; set; }
    
        public virtual EvaluacionDocente EvaluacionDocente { get; set; }
        public virtual Pregunta Pregunta { get; set; }
    }
}
