//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIED
{
    using System;
    using System.Collections.Generic;
    
    public partial class Respuesta_CategoriaPregunta
    {
        public int id { get; set; }
        public Nullable<int> idRespuesta { get; set; }
        public Nullable<int> idCategoriaPregunta { get; set; }
    
        public virtual CategoriaPregunta CategoriaPregunta { get; set; }
        public virtual Respuesta Respuesta { get; set; }
    }
}
