//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIED
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class siedEntities : DbContext
    {
        public siedEntities()
            : base("name=siedEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alumno> Alumnos { get; set; }
        public virtual DbSet<Asignatura> Asignaturas { get; set; }
        public virtual DbSet<Aviso> Avisoes { get; set; }
        public virtual DbSet<AvisosPadre> AvisosPadres { get; set; }
        public virtual DbSet<Calificacione> Calificaciones { get; set; }
        public virtual DbSet<CategoriaPregunta> CategoriaPreguntas { get; set; }
        public virtual DbSet<CicloEscolar> CicloEscolars { get; set; }
        public virtual DbSet<DatosEscuela> DatosEscuelas { get; set; }
        public virtual DbSet<DepartamentosEscuela> DepartamentosEscuelas { get; set; }
        public virtual DbSet<DocumentosAlumno> DocumentosAlumnoes { get; set; }
        public virtual DbSet<EscuelasProcedenciaAlumno> EscuelasProcedenciaAlumnos { get; set; }
        public virtual DbSet<Estado> Estadoes { get; set; }
        public virtual DbSet<FechaCalificacion> FechaCalificacions { get; set; }
        public virtual DbSet<GrupoAsignatura> GrupoAsignaturas { get; set; }
        public virtual DbSet<Grupos> Grupos { get; set; }
        public virtual DbSet<MaestroGrupos> MaestroGrupos { get; set; }
        public virtual DbSet<Maestro> Maestros { get; set; }
        public virtual DbSet<Mensaje> Mensajes { get; set; }
        public virtual DbSet<ModalidadAsignatura> ModalidadAsignaturas { get; set; }
        public virtual DbSet<MomentoCalificacion> MomentoCalificacions { get; set; }
        public virtual DbSet<Municipio> Municipios { get; set; }
        public virtual DbSet<Pai> Pais { get; set; }
        public virtual DbSet<PeriodoEscolar> PeriodoEscolars { get; set; }
        public virtual DbSet<PlanesEstudio> PlanesEstudios { get; set; }
        public virtual DbSet<Semestre> Semestres { get; set; }
        public virtual DbSet<SolicitudBaja> SolicitudBajas { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TipoAlumno> TipoAlumnoes { get; set; }
        public virtual DbSet<TipoAsignatura> TipoAsignaturas { get; set; }
        public virtual DbSet<TipoMaestro> TipoMaestroes { get; set; }
        public virtual DbSet<TurnosEscuela> TurnosEscuelas { get; set; }
        public virtual DbSet<CalificacionesAlumno> CalificacionesAlumnoes { get; set; }
    }
}
