//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIED
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudBaja
    {
        public int IDSolicitud { get; set; }
        public string TipoBaja { get; set; }
        public string Motivo { get; set; }
        public Nullable<int> IDAlumno { get; set; }
        public string NoOficio { get; set; }
        public Nullable<int> IDPeriodo { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual PeriodoEscolar PeriodoEscolar { get; set; }
    }
}
