//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIED
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoMaestro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TipoMaestro()
        {
            this.Maestros = new HashSet<Maestro>();
        }
    
        public int IDTipoMaestro { get; set; }
        public Nullable<byte> Directivo { get; set; }
        public Nullable<byte> SecreAdmin { get; set; }
        public Nullable<byte> SecreAcade { get; set; }
        public Nullable<byte> ControlEsc { get; set; }
        public Nullable<byte> Docente { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Maestro> Maestros { get; set; }
    }
}
